name: Lint on PR/push

on:
  push:
    branches:
      - spio/master
      - master
  pull_request:

jobs:
  markdown-lint:
    name: Lint markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: '**/*.md'
          config_file: .markdownlint.json

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Validate handlebars templates
        run: npx handlebars -e md . > /dev/null
